# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QiitaClientApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QiitaClientApp
  pod 'Alamofire', '~> 5.5'
  pod 'SwiftFormat/CLI', '~> 0.49'
  pod 'SwiftLint'
  pod 'KeychainAccess'
  
end
