# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai06' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai06
  pod 'Alamofire', '~> 5.5'

  target 'kadai06Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kadai06UITests' do
    # Pods for testing
  end

end
